/********************************************************************
* /nfs/hicran/project/panda/SIM/jrauch/genfitStandalone/branches/genfit2/UML/CodeGeneratorOutput/genfitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /nfs/hicran/project/panda/SIM/jrauch/genfitStandalone/branches/genfit2/UML/CodeGeneratorOutput/genfitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablegenfitDict();
extern void G__cpp_setup_inheritancegenfitDict();
extern void G__cpp_setup_typetablegenfitDict();
extern void G__cpp_setup_memvargenfitDict();
extern void G__cpp_setup_globalgenfitDict();
extern void G__cpp_setup_memfuncgenfitDict();
extern void G__cpp_setup_funcgenfitDict();
extern void G__set_cpp_environmentgenfitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../include/AbsFinitePlane.h"
#include "../include/KalmanFitterInfo.h"
#include "../include/ProlateSpacePointMeasurement.h"
#include "../include/TrackCandHit.h"
#include "../include/AbsFitterInfo.h"
#include "../include/MaterialInfo.h"
#include "../include/RectangularFinitePlane.h"
#include "../include/Track.h"
#include "../include/AbsMeasurement.h"
#include "../include/MeasuredStateOnPlane.h"
#include "../include/ReferenceStateOnPlane.h"
#include "../include/TrackPoint.h"
#include "../include/AbsTrackRep.h"
#include "../include/PlanarMeasurement.h"
#include "../include/SpacePointMeasurement.h"
#include "../include/WireMeasurement.h"
#include "../include/DetPlane.h"
#include "../include/PlanarPixelMeasurement.h"
#include "../include/StateOnPlane.h"
#include "../include/WirePointMeasurement.h"
#include "../include/KalmanFittedStateOnPlane.h"
#include "../include/PlanarStripMeasurement.h"
#include "../include/TrackCand.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__genfitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__genfitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__genfitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__genfitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__genfitDictLN_genfit;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLAbsFinitePlane;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLAbsFitterInfo;
extern G__linked_taginfo G__genfitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__genfitDictLN_TVector3;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLDetPlane;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLAbsTrackRep;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLStateOnPlane;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLMeasuredStateOnPlane;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLKalmanFittedStateOnPlane;
extern G__linked_taginfo G__genfitDictLN_MeasurementOnPlane;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLReferenceStateOnPlane;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLKalmanFitterInfo;
extern G__linked_taginfo G__genfitDictLN_vectorlEMeasurementOnPlanecOallocatorlEMeasurementOnPlanegRsPgR;
extern G__linked_taginfo G__genfitDictLN_reverse_iteratorlEvectorlEMeasurementOnPlanecOallocatorlEMeasurementOnPlanegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLTrackPoint;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLAbsMeasurement;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLSpacePointMeasurement;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLProlateSpacePointMeasurement;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLTrackCandHit;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLMaterialInfo;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLRectangularFinitePlane;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLTrack;
extern G__linked_taginfo G__genfitDictLN_vectorlEgenfitcLcLAbsMeasurementmUcOallocatorlEgenfitcLcLAbsMeasurementmUgRsPgR;
extern G__linked_taginfo G__genfitDictLN_reverse_iteratorlEvectorlEgenfitcLcLAbsMeasurementmUcOallocatorlEgenfitcLcLAbsMeasurementmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__genfitDictLN_vectorlEgenfitcLcLKalmanFitterInfocOallocatorlEgenfitcLcLKalmanFitterInfogRsPgR;
extern G__linked_taginfo G__genfitDictLN_reverse_iteratorlEvectorlEgenfitcLcLKalmanFitterInfocOallocatorlEgenfitcLcLKalmanFitterInfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__genfitDictLN_vectorlEgenfitcLcLTrackPointcOallocatorlEgenfitcLcLTrackPointgRsPgR;
extern G__linked_taginfo G__genfitDictLN_reverse_iteratorlEvectorlEgenfitcLcLTrackPointcOallocatorlEgenfitcLcLTrackPointgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__genfitDictLN_vectorlEgenfitcLcLAbsTrackRepmUcOallocatorlEgenfitcLcLAbsTrackRepmUgRsPgR;
extern G__linked_taginfo G__genfitDictLN_reverse_iteratorlEvectorlEgenfitcLcLAbsTrackRepmUcOallocatorlEgenfitcLcLAbsTrackRepmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLPlanarMeasurement;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLWireMeasurement;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLPlanarPixelMeasurement;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLWirePointMeasurement;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLPlanarStripMeasurement;
extern G__linked_taginfo G__genfitDictLN_genfitcLcLTrackCand;
extern G__linked_taginfo G__genfitDictLN_vectorlEgenfitcLcLTrackCandHitcOallocatorlEgenfitcLcLTrackCandHitgRsPgR;
extern G__linked_taginfo G__genfitDictLN_reverse_iteratorlEvectorlEgenfitcLcLTrackCandHitcOallocatorlEgenfitcLcLTrackCandHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
