#include "AbsFinitePlane.h"

namespace genfit {




bool AbsFinitePlane::isInActive(double u, double v)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D33 begin
{
  return false;
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D33 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace genfit */
