#include "AbsMeasurement.h"

namespace genfit {


  /** 
   *  Contains the measurement and covariance in detector coordinates. Detector and hit ids can be used to point back to the original detector hits (clusters etc.).
   */



 MeasurementOnPlane AbsMeasurement::constructMeasurementOnPlane()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--1eeb8d28:13caa78033d:-8000:000000000000120D begin
{
}
// section 127-0-1-1--1eeb8d28:13caa78033d:-8000:000000000000120D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace genfit */
