#include "AbsTrackRep.h"

namespace genfit {


  /** 
   *  Provides functionality to extrapolate a #GFStateOnPlane to another #GFDetPlane, or to the POCA to a line or a point.
   */



AbsTrackRep::extrapolateToPlane(StateOnPlane stateInput, std::shared_ptr<DetPlane> plane, bool stopAtBoundary, StateOnPlane &statePrediction)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D6E begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D6E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

AbsTrackRep::extrapolateToLine()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D73 begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D73 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

AbsTrackRep::extrapolateToPoint()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D75 begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D75 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

AbsTrackRep::extrapolateToCylinder()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D77 begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D77 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

AbsTrackRep::extrapolateToSphere()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D79 begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D79 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

AbsTrackRep::getPos()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D7B begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D7B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

AbsTrackRep::getMom()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D7D begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D7D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int AbsTrackRep::extrapolateToTrackPoint()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-690c17ea:13da6494d87:-8000:0000000000000DEE begin
{
  return 0;
}
// section 127-0-1-1-690c17ea:13da6494d87:-8000:0000000000000DEE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace genfit */
