#include "KalmanFitterInfo.h"

namespace genfit {


  /** 
   *  This class collects all information needed and produced by a Kalman filter or DAF and is specific to one #GFAbsTrackRep of the #GFTrack.
   */



MeasuredStateOnPlane KalmanFitterInfo::getBiasedSmoothedState()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D7F begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D7F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

MeasuredStateOnPlane KalmanFitterInfo::getUnbiasedSmoothedState()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D81 begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:0000000000000D81 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

StateOnPlane KalmanFitterInfo::getBiasedResidual()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:00000000000011B1 begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:00000000000011B1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

StateOnPlane KalmanFitterInfo::getUnbiasedResidual()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:00000000000011B3 begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:00000000000011B3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace genfit */
