#include "Track.h"

namespace genfit {


  /** 
   *  Holds a number of #GFAbsTrackRep, which correspond to the different particle hypotheses or track models which should be fitted.
   *  
   *  Can be created from a TrackCand, then all the information from the TrackCand will go into the Track.
   */



Track::insertPoint(int i, TrackPoint point)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:00000000000011A5 begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:00000000000011A5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Track::removePoint(int i)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:00000000000011A8 begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:00000000000011A8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Track::mergeTrack(int i, Track other)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:00000000000011AA begin
{
}
// section 127-0-1-1-60a1652a:13cb03ca74a:-8000:00000000000011AA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace genfit */
